# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerarium', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='background',
            field=models.ImageField(null=True, upload_to='backgrounds'),
        ),
    ]
