# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 23:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerarium', '0003_post_background'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='background',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m'),
        ),
    ]
