# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 02:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerarium', '0014_auto_20160225_0304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='itinerarium/static/images/%Y/%m'),
        ),
    ]
