# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-25 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerarium', '0016_auto_20160225_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='images/%Y/%m'),
        ),
    ]
